// Register-tiled matmul: C = A × B (+ D if fused_add)
// One skeleton for both tile sizes (BM=BN=$BM_U, KTILE=$K_TILE_U, workgroup
// [16,16,1]): TM=TN=4 with 16 accumulators for the 64×64 tile, TM=TN=2
// with 4 accumulators for the 32×32 small tile. The unrolled accumulator
// declarations, FMA body, and store array are generated by
// `codegen::tiled_matmul_body`.
//
// Shared memory uses padded strides to distribute consecutive rows across
// banks. The per-thread register mapping still affects bank conflicts;
// codegen supplies the column mapping for both shared reads and output stores.
//
// Template variables: BM_U/TM_U/B_STRIDE_U/STAGE_EPT_U and shared sizes
// (tile geometry), A_INDEX/B_INDEX (global index), A_ROW/COL, B_ROW/COL
// (tile mapping), TILE_ROW/C_INDEX (dispatch/storage layout),
// ACC_DECL/COMPUTE_BODY/ACC_ARRAY (generated unrolls),
// FUSED_ADD_DECL/STORE_BODY (addend/epilogue), B_* (weight format).

$ENABLE_F16
struct Params {
    m: u32,
    n: u32,
    k: u32,
    _pad: u32,
}

var<storage> matrix_a: array<f32>;
var<storage> matrix_b: $B_STORAGE_TYPE;
var<storage, read_write> matrix_c: array<f32>;
$FUSED_ADD_DECL
var<uniform> params: Params;
var<workgroup> shared_a: array<f32, $SHARED_A_SIZE>;
var<workgroup> shared_b: array<f32, $SHARED_B_SIZE>;
$B_DEQUANT_FN

@compute @workgroup_size(16, 16)
fn main(@builtin(workgroup_id) wgid: vec3<u32>, @builtin(local_invocation_id) lid: vec3<u32>) {
    let tx = lid.x;
    let ty = lid.y;
    let tile_row = ($TILE_ROW) * $BM_U;
    let tile_col = wgid.x * $BM_U;
    let tid = ty * 16u + tx;

    $ACC_DECL

    var t = 0u;
    loop {
        if t >= params.k { break; }

        // Stage A with a padded shared-memory stride.
        for (var e = 0u; e < $STAGE_EPT_U; e++) {
            let flat = tid + e * 256u;
            let row_local = $A_ROW;
            let col_local = $A_COL;
            let a_row = tile_row + row_local;
            let a_col = t + col_local;
            let in_bounds = (a_row < params.m) && (a_col < params.k);
            shared_a[row_local * $A_STRIDE_U + col_local] = select(0.0, matrix_a[$A_INDEX], in_bounds);
        }

        // Load B tile into shared_b[KTILE×BN]. Default: one element per
        // iteration. Q4 large-tile replaces this with pack8 staging.
        $B_STAGE_BODY

        workgroupBarrier();

        for (var kk = 0u; kk < $K_TILE_U; kk++) {
            $COMPUTE_BODY
        }

        workgroupBarrier();
        t += $K_TILE_U;
    }

    // Store results with bounds check and optional fused epilogue
    let s = $ACC_ARRAY;
    for (var i = 0u; i < $TM_U; i++) {
        for (var j = 0u; j < $TM_U; j++) {
            let row = tile_row + ty * $TM_U + i;
            let col = tile_col + $OUTPUT_COLUMN;
            if row < params.m && col < params.n {
                let idx = $C_INDEX;
                $STORE_BODY
            }
        }
    }
}
