//! Numerical parity test: meganeura's EfficientNetV2-S features[0:6]
//! vs torchvision's reference output.
//!
//! The reference is generated by `bench/dump_efficientnet_v2_reference.py`
//! and lives in `bench/results/`. The test SKIPs (passes silently) if
//! either file is missing — regenerate with:
//!
//!     /x/Code/inferena/.venv/bin/python bench/dump_efficientnet_v2_reference.py
//!
//! Tolerances:
//!   * max-abs error ≤ 5e-2 (BN fusion + bf16-free f32 path; CPU GPU
//!     mismatch on EfficientNet's deep tower drifts a bit per layer).
//!   * relative error per-element where torchvision's value > 1.0 ≤ 1%.

use meganeura::data::safetensors::SafeTensorsModel;
use meganeura::models::efficientnet;
use meganeura::{Graph, build_inference_session};

const SAFETENSORS_PATH: &str = "bench/results/efficientnet_v2s.safetensors";
const REFERENCE_PATH: &str = "bench/results/efficientnet_v2s_reference.json";

fn parse_f32_array(json: &str, key: &str) -> Vec<f32> {
    let needle = format!("\"{key}\": [");
    let start = json.find(&needle).expect(key) + needle.len();
    let end = start + json[start..].find(']').unwrap();
    json[start..end]
        .split(',')
        .map(|s| s.trim().parse::<f32>().unwrap())
        .collect()
}

#[test]
fn efficientnet_v2s_matches_torchvision() {
    if !std::path::Path::new(SAFETENSORS_PATH).exists()
        || !std::path::Path::new(REFERENCE_PATH).exists()
    {
        eprintln!(
            "SKIP: bench/results/efficientnet_v2s.{{safetensors,reference.json}} \
             not found — run bench/dump_efficientnet_v2_reference.py first."
        );
        return;
    }

    let json = std::fs::read_to_string(REFERENCE_PATH).unwrap();
    let input = parse_f32_array(&json, "input");
    let expected = parse_f32_array(&json, "output");
    assert_eq!(input.len(), 1 * 3 * 192 * 192);
    assert_eq!(expected.len(), 160 * 12 * 12);

    let weights = SafeTensorsModel::load(SAFETENSORS_PATH.into())
        .expect("loading safetensors");

    // Build the graph + session.
    let mut g = Graph::new();
    let out = efficientnet::build_graph(&mut g, /*batch=*/ 1);
    g.set_outputs(vec![out]);
    let mut session = build_inference_session(&g);

    // Set every parameter from the safetensors file. This catches both
    // missing-from-file and missing-from-graph at load time.
    for name in efficientnet::weight_names() {
        let data = weights
            .tensor_f32(&name)
            .unwrap_or_else(|e| panic!("loading parameter '{name}': {e}"));
        session.set_parameter(&name, &data);
    }

    session.set_input("image", &input);
    session.step();
    session.wait();

    let actual = session.read_output(expected.len());
    assert_eq!(actual.len(), expected.len());

    let mut max_abs = 0.0f32;
    let mut max_rel = 0.0f32;
    let mut max_idx = 0;
    for (i, (&a, &e)) in actual.iter().zip(expected.iter()).enumerate() {
        let abs = (a - e).abs();
        if abs > max_abs {
            max_abs = abs;
            max_idx = i;
        }
        if e.abs() > 1.0 {
            let rel = abs / e.abs();
            if rel > max_rel {
                max_rel = rel;
            }
        }
    }
    eprintln!(
        "max_abs = {:.4e} at idx {} (got {:.4} vs expected {:.4}); max_rel (|exp|>1) = {:.4e}",
        max_abs, max_idx, actual[max_idx], expected[max_idx], max_rel
    );

    assert!(
        max_abs < 5e-2,
        "max-abs error {:.4e} exceeds 5e-2 tolerance; idx={} got={:.4} exp={:.4}",
        max_abs,
        max_idx,
        actual[max_idx],
        expected[max_idx]
    );
    assert!(
        max_rel < 1e-2,
        "max-rel error {:.4e} (where |expected| > 1) exceeds 1% tolerance",
        max_rel
    );
}
