//! Correctness test: compare meganeura SmolLM2-135M logits against PyTorch reference.
//!
//! Requires `bench/results/smollm2_ref_logits.bin` generated by:
//!   python bench/dump_smollm2_logits.py
//!
//! Run: cargo test --test smollm2_correctness -- --ignored

use meganeura::{
    Graph, build_inference_session,
    data::safetensors::SafeTensorsModel,
    models::smollm2::{self, SmolLM2Config},
};
use std::collections::HashSet;

/// Reference values from PyTorch (HuggingFace transformers) with SmolLM2-135M.
/// Prompt: "The meaning of life is"
const TOKEN_IDS: &[u32] = &[504, 2455, 282, 1029, 314];
const SEQ_LEN: usize = 5;
const VOCAB_SIZE: usize = 49152;
/// Greedy argmax at each position from PyTorch.
const REF_GREEDY: &[u32] = &[808, 282, 260, 314, 288];

fn load_weights(
    session: &mut meganeura::Session,
    model: &SafeTensorsModel,
    config: &SmolLM2Config,
) {
    let transposed = smollm2::transposed_weight_names(config);
    let transposed_set: HashSet<&str> = transposed.iter().map(|s| s.as_str()).collect();

    for (name, _) in session.plan().param_buffers.clone() {
        // Skip fused parameters — auto-populated when source params are loaded
        if !model.tensor_info().contains_key(&name) && name != "lm_head.weight" {
            continue;
        }
        if name == "lm_head.weight" {
            if model.tensor_info().contains_key("lm_head.weight") {
                let data = if transposed_set.contains(name.as_str()) {
                    model.tensor_f32_auto_transposed(&name)
                } else {
                    model.tensor_f32_auto(&name)
                };
                session.set_parameter(&name, &data.unwrap_or_else(|e| panic!("{name}: {e}")));
            } else {
                let data = model
                    .tensor_f32_auto_transposed("model.embed_tokens.weight")
                    .expect("embed_tokens");
                session.set_parameter("lm_head.weight", &data);
            }
        } else if transposed_set.contains(name.as_str()) {
            let data = model
                .tensor_f32_auto_transposed(&name)
                .unwrap_or_else(|e| panic!("{name}: {e}"));
            session.set_parameter(&name, &data);
        } else {
            let data = model
                .tensor_f32_auto(&name)
                .unwrap_or_else(|e| panic!("{name}: {e}"));
            session.set_parameter(&name, &data);
        }
    }
}

#[test]
#[ignore] // Requires model download + reference logits on disk
fn smollm2_logits_match_pytorch() {
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("warn"))
        .try_init()
        .ok();

    // Load reference logits
    let bin_path = "bench/results/smollm2_ref_logits.bin";
    let bin_data = std::fs::read(bin_path).unwrap_or_else(|e| {
        panic!(
            "Missing reference logits ({bin_path}): {e}\n\
             Run: python bench/dump_smollm2_logits.py"
        )
    });
    let ref_logits: Vec<f32> = bin_data
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    assert_eq!(ref_logits.len(), SEQ_LEN * VOCAB_SIZE);

    let config = SmolLM2Config::smollm2_135m();
    let mut g = Graph::new();
    let logits = smollm2::build_graph(&mut g, &config, SEQ_LEN);
    g.set_outputs(vec![logits]);

    let mut session = build_inference_session(&g);

    let model =
        SafeTensorsModel::download("HuggingFaceTB/SmolLM2-135M").expect("failed to download model");
    load_weights(&mut session, &model, &config);

    // Run inference
    session.set_input_u32("token_ids", TOKEN_IDS);
    session.step();
    session.wait();

    let mega_logits = session.read_output(SEQ_LEN * VOCAB_SIZE);
    assert_eq!(mega_logits.len(), SEQ_LEN * VOCAB_SIZE);

    // Compare per-position
    let mut greedy_match = 0;
    let mut total_max_err = 0.0_f32;

    for pos in 0..SEQ_LEN {
        let offset = pos * VOCAB_SIZE;
        let mega_pos = &mega_logits[offset..offset + VOCAB_SIZE];
        let ref_pos = &ref_logits[offset..offset + VOCAB_SIZE];

        let pos_max_err: f32 = mega_pos
            .iter()
            .zip(ref_pos)
            .map(|(a, b)| (a - b).abs())
            .fold(0.0, f32::max);

        let mega_argmax = mega_pos
            .iter()
            .enumerate()
            .max_by(|a, b| a.1.partial_cmp(b.1).unwrap())
            .unwrap()
            .0 as u32;

        if mega_argmax == REF_GREEDY[pos] {
            greedy_match += 1;
        }

        eprintln!(
            "pos {pos}: max_err={pos_max_err:.4e}, mega_argmax={mega_argmax}, ref={} [{}]",
            REF_GREEDY[pos],
            if mega_argmax == REF_GREEDY[pos] {
                "MATCH"
            } else {
                "MISMATCH"
            }
        );

        total_max_err = total_max_err.max(pos_max_err);
    }

    eprintln!("\nGreedy matches: {greedy_match}/{SEQ_LEN}");
    eprintln!("Overall max abs error: {total_max_err:.4e}");

    // Position 0 should be nearly exact (RoPE is identity at pos 0)
    let pos0_max_err: f32 = mega_logits[..VOCAB_SIZE]
        .iter()
        .zip(&ref_logits[..VOCAB_SIZE])
        .map(|(a, b)| (a - b).abs())
        .fold(0.0, f32::max);
    assert!(
        pos0_max_err < 0.01,
        "Position 0 should be very precise, got max_err={pos0_max_err:.4e}"
    );

    // At least 3/5 greedy tokens should match (f32 accumulation through
    // 30 layers on software Vulkan can diverge enough to flip close races)
    assert!(
        greedy_match >= 3,
        "Too few greedy matches: {greedy_match}/5 (expected >= 3)"
    );
}
