#!/usr/bin/env python3
"""Package the P3HPC source ZIP and supplementary ZIP (no GPU).

Run from anywhere after building `paper/p3hpc/main.pdf`:

    python3 paper/p3hpc/artifact/submission.py "$HOME/Downloads/p3hpc" \\
        --pdf paper/p3hpc/main.pdf --output paper/p3hpc/submission

The records stream is regenerated from the campaign archives with
`cohort.py --bundle`, so the supplement never mixes checkers and records.
"""

import argparse
import hashlib
import io
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import zipfile

HERE = Path(__file__).resolve().parent
P3HPC = HERE.parent
PAPER = P3HPC.parent
ZIP_TIME = (1980, 1, 1, 0, 0, 0)
TABLES = ("devices", "qualification", "ratios", "preparation", "search", "scaling",
          "portability", "ratio-plot", "ablation")
SOURCE_README = """# Meganeura P3HPC paper sources

Build from `paper/p3hpc` with a TeX Live installation that has the
PostScript base fonts (Times, Courier, Helvetica), booktabs, pgf/TikZ,
microtype, xcolor and tagging:

    latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex

`main.bbl` is included for builds without BibTeX. The bibliography combines
`paper/references.bib` and `paper/p3hpc/references.bib`. Tables in
`paper/p3hpc/tables` are generated by the supplement's analyzers; the
Artifact Description is `artifact-description.tex` with `sc26repro.sty`.
"""


def write(archive, name, data):
    info = zipfile.ZipInfo(name, ZIP_TIME)
    info.compress_type = zipfile.ZIP_DEFLATED
    info.external_attr = 0o644 << 16
    archive.writestr(info, data)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("archives", type=Path, help="directory holding the campaign archives and search-ablation.tgz")
    parser.add_argument("--pdf", type=Path, required=True, help="built paper PDF to copy beside the ZIPs")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    bbl = args.pdf.with_suffix(".bbl")
    if not bbl.exists():
        sys.exit(f"missing {bbl}; build the PDF with BibTeX first")

    files = {}
    for name in ("main.tex", "artifact-description.tex", "sc26repro.sty", "IEEEtran.cls",
                 "IEEEtran.bst", "references.bib"):
        files[f"paper/p3hpc/{name}"] = (P3HPC / name).read_bytes()
    files["paper/p3hpc/main.bbl"] = bbl.read_bytes()
    for table in TABLES:
        files[f"paper/p3hpc/tables/{table}.tex"] = (P3HPC / "tables" / f"{table}.tex").read_bytes()
    files["paper/references.bib"] = (PAPER / "references.bib").read_bytes()
    files["paper/figures/dinovision-quest3s.jpg"] = (PAPER / "figures/dinovision-quest3s.jpg").read_bytes()
    with zipfile.ZipFile(args.output / "meganeura-p3hpc-source.zip", "w") as archive:
        write(archive, "README.md", SOURCE_README)
        for name, data in sorted(files.items()):
            write(archive, name, data)

    with tempfile.TemporaryDirectory() as directory:
        bundle = Path(directory) / "records.jsonl.xz"
        subprocess.run([sys.executable, str(HERE / "cohort.py"), str(args.archives), "--bundle", str(bundle)],
                       check=True, stdout=subprocess.DEVNULL)
        files = {"README.md": (HERE / "SUPPLEMENT.md").read_bytes(),
                 "records.jsonl.xz": bundle.read_bytes(),
                 "search-ablation.tgz": (args.archives / "search-ablation.tgz").read_bytes()}
    for name in ("cohort.py", "search_ablation.py", "footprint.py", "cohort.sha256", "search-ablation.sha256"):
        files[name] = (HERE / name).read_bytes()
    for table in TABLES:
        files[f"tables/{table}.tex"] = (P3HPC / "tables" / f"{table}.tex").read_bytes()
    manifest = "".join(f"{hashlib.sha256(data).hexdigest()}  {name}\n" for name, data in sorted(files.items()))
    files["MANIFEST.sha256"] = manifest.encode()
    with zipfile.ZipFile(args.output / "meganeura-p3hpc-supplement.zip", "w") as archive:
        for name, data in sorted(files.items()):
            write(archive, f"meganeura-p3hpc-supplement/{name}", data)
    shutil.copy2(args.pdf, args.output / "meganeura-p3hpc.pdf")
    for name in ("meganeura-p3hpc.pdf", "meganeura-p3hpc-source.zip", "meganeura-p3hpc-supplement.zip"):
        path = args.output / name
        print(f"{hashlib.sha256(path.read_bytes()).hexdigest()}  {name}  ({path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
